apiVersion: v1
kind: PersistentVolume
metadata:
   name: minio-local-pv
spec:
   accessModes:
   - ReadWriteOnce
   capacity:
      storage: 30Gi
   hostPath:
      path: /export
   volumeMode: Filesystem
   persistentVolumeReclaimPolicy: Retain
   storageClassName: minio-local
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
